describe('Going through the Flag For Enforcement Workflow', function () {

    beforeEach(() => {
        cy.login();
        cy.visit('/plugins/init-workflow');
    });

    // dd-mm-yyyy, the format the date widgets render and the summary step shows.
    const todayString = () => {
        const today = new Date();
        return [
            String(today.getDate()).padStart(2, '0'),
            String(today.getMonth() + 1).padStart(2, '0'),
            today.getFullYear(),
        ].join('-');
    };

    it('Go through the workflow and populate all fields', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.wait(1000)
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.get('[aria-label="Case Reference"]').should('be.visible').type('Case Ref');
        cy.wait(2000);
        cy.type_ckeditor('editor2', 'test reason for enforcement');
        cy.pickRelationshipFirst('Flagged by');

        // Flagged Date has to be typed in. Nothing defaults it — the constants
        // in coral/functions/notify_enforcement.py are unused — so leaving it
        // blank made the summary step below render "Flagged Date: No data
        // provided for this input" and the assertion never found
        // "Flagged Date Value:".
        cy.get('input[aria-label^="Flagged Date"]').filter(':visible').first()
            .type(`${todayString()}{enter}`, { force: true });
        cy.get('input[aria-label^="Flagged Date"]').filter(':visible').first()
            .should('have.value', todayString());

        cy.get('[aria-label="Select resources, Add new Relationship"]').click();
        cy.wait(1000);
        cy.select2Search('HA/02');
        cy.wait(1500);
        cy.get('.select2-results__option').contains('HA/02').click();
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.wait(2000);
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Case Reference Number:').siblings().should('have.text', 'Case Ref');
        cy.contains('Description:').siblings().should('have.text', 'test reason for enforcement');

        cy.contains('Flagged Date Value:').siblings().should('contain', todayString());
        cy.contains('Associated Resources:').siblings().should('have.text', 'HA/02 Testing');
        cy.wait(900);
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Enforcement ID', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.wait(1000)
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        
        // Enforcement Details Tab
        // Nothing is filled in on this step, so it stays unmodified and the
        // footer button reads "Next Step" rather than "Save and Continue" —
        // see coral/templates/views/components/plugins/workflow.htm.
        cy.get('[aria-label="Case Reference"]', { timeout: 20000 }).should('be.visible');
        cy.workflowNext();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().invoke('text').as('enforcementId')
        cy.contains('Save and Complete Workflow').click();

        cy.visit('/search?paging-filter=1&tiles=true');
    });

    it('Workflow with only Case Reference', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.wait(1000)
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.get('[aria-label="Case Reference"]').should('be.visible').type('Case Ref');
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Case Reference Number:').siblings().should('have.text', 'Case Ref');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Reason For Enforcement', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.get('[aria-label="Case Reference"]', { timeout: 20000 }).should('be.visible');
        cy.wait(1000);
        cy.type_ckeditor('editor2', 'test reason for enforcement');
        cy.wait(2000);
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.wait(2000);
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Description:').siblings().should('have.text', 'test reason for enforcement');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Flagged By', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.get('[aria-label="Case Reference"]', { timeout: 20000 }).should('be.visible');
        cy.pickRelationshipFirst('Flagged by');
        cy.wait(500);
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Flagged By using Organisation', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.get('[aria-label="Case Reference"]', { timeout: 20000 }).should('be.visible');
        cy.pickRelationshipByName('Flagged by', 'Test Organisation');
        cy.wait(500);
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Actor:').siblings().should('have.text', 'Test Organisation');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Flagged By using both an Organisation and a Person', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.get('[aria-label="Case Reference"]', { timeout: 20000 }).should('be.visible');
        cy.pickRelationshipByName('Flagged by', 'Test Organisation');
        cy.wait(2000);
        cy.pickRelationshipByName('Flagged by', 'Test Person');
        cy.wait(500);
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Actor:').siblings().should('have.text', 'Test Person, Test Organisation');
        cy.contains('Save and Complete Workflow').click();
    });
});
