describe('Going through the Flag For Enforcement Workflow', function () {

    beforeEach(() => {
        cy.login();
        cy.visit('/plugins/init-workflow');
    });

    // dd-mm-yyyy, the format the date widgets render and the summary step shows.
    const todayString = () => {
        const today = new Date();
        return [
            String(today.getDate()).padStart(2, '0'),
            String(today.getMonth() + 1).padStart(2, '0'),
            today.getFullYear(),
        ].join('-');
    };

    it('Go through the workflow and populate all fields', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.wait(1000)
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.get('[aria-label="Case Reference"]').should('be.visible').type('Case Ref');
        cy.wait(2000);
        cy.type_ckeditor('editor2', 'test reason for enforcement');

        // Flagged Date has to be typed in. Nothing defaults it - the constants
        // in coral/functions/notify_enforcement.py are unused - so leaving it
        // blank made the summary step below render "Flagged Date: No data
        // provided for this input" and the assertion never found
        // "Flagged Date Value:".
        cy.get('input[aria-label="Flagged Date"]').first().scrollIntoView();
        cy.get('input[aria-label="Flagged Date"]').first()
            .type(`${todayString()}{enter}`, { force: true })
            .should('have.value', todayString());

        cy.pickRelationshipByName('Flagged by', 'Test Person');

        cy.get('[aria-label="Select resources, Add new Relationship"]').click();
        cy.wait(1000);
        cy.select2Search('HA/02');
        cy.wait(1500);
        // One chain, so the option that is captured is the option that is clicked:
        // a second `cy.get('.select2-results__option')` can land mid-re-render and
        // hand `contains` an empty subject, which Cypress 13+ treats as an error.
        cy.contains('.select2-results__option', 'HA/02').then(($option) => {
            cy.wrap($option.text().trim()).as('associatedResourceName');
            cy.wrap($option).click();
        });
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.wait(2000);
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Case Reference Number:').siblings().should('have.text', 'Case Ref');
        cy.contains('Description:').siblings().should('have.text', 'test reason for enforcement');

        cy.contains('Flagged Date Value:').siblings().should('contain', todayString());
        cy.get('@associatedResourceName').then((name) => {
            cy.contains('Associated Resources:').siblings().should('have.text', name.trim());
        });
        cy.contains('Actor:').siblings().should('have.text', 'Test Person');
        cy.wait(900);
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Enforcement ID', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.wait(1000)
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        
        // Enforcement Details Tab
        // Nothing is filled in on this step, so it stays unmodified and the
        // footer button reads "Next Step" rather than "Save and Continue" -
        // see coral/templates/views/components/plugins/workflow.htm.
        cy.get('[aria-label="Case Reference"]', { timeout: 20000 }).should('be.visible');
        cy.workflowNext();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Case Reference', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.wait(1000)
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.get('[aria-label="Case Reference"]').should('be.visible').type('Case Ref');
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Case Reference Number:').siblings().should('have.text', 'Case Ref');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Reason For Enforcement', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.get('[aria-label="Case Reference"]', { timeout: 20000 }).should('be.visible');
        cy.wait(1000);
        cy.type_ckeditor('editor2', 'test reason for enforcement');
        cy.wait(2000);
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.wait(2000);
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Description:').siblings().should('have.text', 'test reason for enforcement');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Flagged By', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.get('[aria-label="Case Reference"]', { timeout: 20000 }).should('be.visible');
        cy.pickRelationshipByName('Flagged by', 'Test Person');
        cy.wait(500);
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Actor:').siblings().should('have.text', 'Test Person');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Flagged By using Organisation', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.get('[aria-label="Case Reference"]', { timeout: 20000 }).should('be.visible');
        cy.pickRelationshipByName('Flagged by', 'Test Organisation');
        cy.wait(500);
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Actor:').siblings().should('have.text', 'Test Organisation');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Flagged By using both an Organisation and a Person', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value');
        cy.get('[aria-label="Enforcement ID"]').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.get('[aria-label="Case Reference"]', { timeout: 20000 }).should('be.visible');
        cy.pickRelationshipByName('Flagged by', 'Test Organisation');
        cy.wait(2000);
        cy.pickRelationshipByName('Flagged by', 'Test Person');
        cy.wait(500);
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Actor:').siblings().should('have.text', 'Test Person, Test Organisation');
        cy.contains('Save and Complete Workflow').click();
    });
});
