# Generated by Django 2.2.6 on 2019-11-12 13:07

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid
from arches.app.models.models import ResourceInstance


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coral", "8010_graphql_etlmodule"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationLink",
            fields=[
                ("registrationlinkid", models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("used", models.DateTimeField(null=True)),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="models.ResourceInstance")),
                ("metadata", models.JSONField(blank=True, db_column="metadata", null=True)),
            ],
            options={"db_table": "registration_links", "managed": True,},
        ),
    ]
