# Generated by Django 4.2.16 on 2025-03-21 12:00

from django.db import migrations

def add_notification_types(apps, schema_editor):
    NotificationType = apps.get_model("models", "NotificationType")

    NotificationType.objects.get_or_create(
        typeid="f49995b9-59ea-4f85-adbb-0e3a60587bd6",
        defaults={
            "name": "Scheduled Monument Management Notifications",
            "emailtemplate": "email/general_notification.htm",
            "emailnotify": True,
            "webnotify": True,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '8011_registration_link_model'),
    ]

    operations = [
        migrations.RunPython(add_notification_types)
    ]
