# Generated by Django 4.2.16 on 2025-03-20 15:03

from django.db import migrations

def add_notification_types(apps, schema_editor):
    NotificationType = apps.get_model("models", "NotificationType")

    NotificationType.objects.get_or_create(
        typeid="e15c6b6e-0526-45fa-b004-d382c5e8f5a5",
        defaults={
            "name": "Enforcement Notifications",
            "emailtemplate": "email/general_notification.htm",
            "emailnotify": True,
            "webnotify": True,
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('coral', '8011_registration_link_model'),
    ]

    operations = [
        migrations.RunPython(add_notification_types)
    ]
