ARG VERSION
ARG ARCHES_PROJECT
FROM arches_${ARCHES_PROJECT}_static:$VERSION as arches_static

FROM arches_$ARCHES_PROJECT:$VERSION as arches

COPY --from=arches_static /usr/share/nginx/html/CACHE/manifest.json /static_root/CACHE/manifest.json

