describe('Going through the Archive Cataloguing Workflow', function () {

    beforeEach(() => {
        cy.login();
        cy.visit('http://localhost:8000/plugins/init-workflow');
    });

    it('Go through the workflow and populate all fields', function () {
        cy.contains('Workflows');
        cy.contains('Archive Cataloguing').click();
        cy.contains('Start New').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Archive Source Details
        cy.wait(900);
        cy.get('input[aria-label="Archive Source Name"]').should('be.visible').type('Test Source Name');
        cy.get('[aria-label="Subtitle"]').should('be.visible').type('Test Subtitle');
        cy.get('[aria-label="File ID (key)"]').should('be.visible').type('TestId');
        cy.get('span').contains('Archive Source Type').should('be.visible').siblings('.archive_source_type').click();
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.get('span').contains('File Status').siblings('.col-xs-12').click();
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.type_ckeditor('editor1', 'test description');
        cy.wait(500);
        cy.contains('Save and Continue').click();
    });

});
