describe('Going through the Archive Cataloguing Workflow', function () {

    beforeEach(() => {
        cy.login();
        cy.visit('http://localhost:8000/plugins/init-workflow');
    });

    it('Start new and go through the workflow and populate all fields', function () {
        cy.contains('Workflows');
        cy.contains('Archive Cataloguing').click();
        cy.contains('Start New').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.get('.workflow-nav-tab.disabled').should('have.length', 4);
        cy.contains('Save and Continue').click();

        // Archive Source Details
        cy.wait(900);
        cy.get('input[aria-label="File Title"]').should('be.visible').type('Test Source Name');
        cy.get('[aria-label="Subtitle"]').should('be.visible').type('Test Subtitle');
        cy.get('[aria-label="File ID (key)"]').should('be.visible').type('TestId');
        cy.get('span').contains('Archive Source Type').should('be.visible').siblings('.archive_source_type').click();
        cy.wait(500);
        cy.get('.select2-results__options li').contains('Genre').click();
        cy.get('span').contains('File Status').siblings('.col-xs-12').click();
        cy.wait(500);
        cy.get('.select2-results__options li').contains('Destroyed');
        cy.get('.select2-results__options li').contains('For Review');
        cy.get('.select2-results__options li').contains('Closed');
        cy.get('.select2-results__options li').contains('Open');
        cy.get('.select2-results__options li').contains('Destroyed').click();
        cy.type_ckeditor('editor1', 'test description');
        cy.wait(500);
        cy.contains('Save and Continue').click();

        // Archive Source Creation
        cy.wait(500);
        cy.get('input[aria-label="Author Name"]').should('be.visible').type('Test Author Name');
        cy.get('input[aria-label="Editor Name(s)"]').should('be.visible').type('Test Editor Name');
        cy.get('[aria-label="Start Date"]').scrollIntoView().should('be.visible').click();
        cy.get('input[aria-label="Start Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
        cy.get('[aria-label="End Date"]').scrollIntoView().should('be.visible').click();
        cy.get('input[aria-label="End Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
        cy.type_ckeditor('editor3', 'test statement of responsibility');
        cy.wait(500);
        cy.contains('Save and Continue').click();

        // Repository Storage Location
        cy.wait(1000);
        cy.get('span').contains('Responsible Team').should('be.visible').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Person');
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.get('span').contains('Storage Building Name').should('be.visible').siblings('.col-xs-12').click();
        cy.get('.select2-results__options li').contains('PRONI').click();
        cy.get('input[aria-label="Storage Room Name"]').should('be.visible').type('Test Storage Room Name');
        cy.get('input[aria-label="Storage Shelf Name"]').should('be.visible').type('Test Storage Shelf Name');
        cy.get('input[aria-label="Storage Box Name"]').should('be.visible').type('Test Storage Box Name');
        cy.contains('Save and Continue').click();

        // Archive Loan History
        cy.wait(500);
        cy.get('span').contains('Person or Organization').should('be.visible').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Person');
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.get('[aria-label="Start Date"]').scrollIntoView().should('be.visible').click();
        cy.get('[aria-label="Start Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
        cy.get('[aria-label="End Date"]').scrollIntoView().should('be.visible').click();
        cy.get('[aria-label="End Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
        cy.get('.workflow-component-element').get('.btn.btn-workflow-tile.btn-success').should('be.visible').contains('Add').click();

        // Verify data gets added
        cy.get('.wf-step-multi-tile-container').contains('Archive Loan History').siblings().children('div').children().contains('Test Person');
        // Dates shouldn't be empty
        cy.get('.archive_holder_start_date').last().should('not.have.text');
        cy.get('.archive_holder_start_date').last().should('not.have.text', '');
        cy.get('.archive_holder_end_date').last().should('not.have.text');
        cy.get('.archive_holder_end_date').last().should('not.have.text', '');

        cy.get('.wf-multi-tile-step-card-controls').contains('Remove').click();
        cy.get('.wf-multi-tile-step-list-empty').contains('No Archive Loan History added yet. Add one or multiple Archive Loan History').should('be.visible');

        cy.get('span').contains('Person or Organization').should('be.visible').siblings('.row').click();
        cy.get('.select2-search__field').type('John Doe');
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.get('[aria-label="Start Date"]').scrollIntoView().should('not.have.value');
        cy.get('[aria-label="Start Date"]').scrollIntoView().should('not.have.value', '');
        cy.get('[aria-label="End Date"]').scrollIntoView().should('not.have.value');
        cy.get('[aria-label="End Date"]').scrollIntoView().should('not.have.value', '');
        cy.get('.workflow-component-element').get('.btn.btn-workflow-tile.btn-success').should('be.visible').contains('Add').click();

        // Verify data gets added
        cy.get('.wf-step-multi-tile-container').contains('Archive Loan History').siblings().children('div').children().contains('John Doe');
        cy.get('.archive_holder_start_date').last().should('not.have.text', 'None');
        cy.get('.archive_holder_end_date').last().should('not.have.text', 'None');

        cy.get('.ion-android-cloud-done').siblings().contains('Save').click();
        cy.wait(500);
        cy.contains('Save and Complete Workflow').click();
    });

    it('Open up the created archive and verify the information', function () {
        cy.contains('Workflows');
        cy.contains('Archive Cataloguing').click();
       
        cy.get('[aria-label="Start new or please select from below"]').should('be.visible').click();
        cy.get('.select2-results__options li').contains('Test Source Name').click();
        cy.contains('Open Selected').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Next Step').click();

        // Archive Source Details
        cy.wait(900);
        cy.get('input[aria-label="File Title"]').should('have.value', 'Test Source Name');
        cy.get('[aria-label="Subtitle"]').should('have.value', 'Test Subtitle');
        cy.get('[aria-label="File ID (key)"]').should('have.value', 'TestId');
        cy.get('[aria-label="Genre"]').scrollIntoView();
        cy.get('[aria-label="Destroyed"]');
        cy.contains('Next Step').click();

        // Archive Source Creation
        cy.wait(500);
        cy.get('input[aria-label="Author Name"]').should('have.value', 'Test Author Name');
        cy.get('input[aria-label="Editor Name(s)"]').should('have.value', 'Test Editor Name');
        cy.get('input[aria-label="Start Date"]').should('not.have.value');
        cy.get('input[aria-label="Start Date"]').should('not.have.value', '');
        cy.get('input[aria-label="End Date"]').should('not.have.value');
        cy.get('input[aria-label="End Date"]').should('not.have.value', '');
        cy.contains('Next Step').click();

        // Repository Storage Location
        cy.get('.rr-table-row').contains('Test Person');
        cy.get('[aria-label="PRONI"]');
        cy.get('input[aria-label="Storage Room Name"]').should('have.value', 'Test Storage Room Name');
        cy.get('input[aria-label="Storage Shelf Name"]').should('have.value', 'Test Storage Shelf Name');
        cy.get('input[aria-label="Storage Box Name"]').should('have.value', 'Test Storage Box Name');
        cy.contains('Next Step').click();

        // Verify data gets added
        cy.get('.wf-step-multi-tile-container').contains('Archive Loan History').siblings().children('div').children().contains('Test Person');
        // Dates shouldn't be empty
        cy.get('.archive_holder_start_date').last().should('not.have.text', 'None');
        cy.get('.archive_holder_end_date').last().should('not.have.text', 'None');

        cy.contains('Save and Complete Workflow').click();
    });

    // START OF Archive Reference Tab individual fields tests 
    it('Populate just Resource ID', function () {
        cy.contains('Workflows');
        cy.contains('Archive Cataloguing').click();
        cy.contains('Start New').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.get('.workflow-nav-tab.disabled').should('have.length', 4);
        cy.contains('Save and Continue').click();

        cy.contains('Save and Complete Workflow').click();
    });
    // END OF Archive Reference Tab individual fields tests 

    // START OF Archive Source Details Tab individual field tests
    it('Populate just File Title', function () {
        cy.contains('Workflows');
        cy.contains('Archive Cataloguing').click();
        cy.contains('Start New').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.get('.workflow-nav-tab.disabled').should('have.length', 4);
        cy.contains('Save and Continue').click();

        // Archive Source Details
        cy.wait(900);
        cy.get('input[aria-label="File Title"]').should('be.visible').type('Test Source Name');
        cy.contains('Save and Continue').click();
        cy.contains('Save and Complete Workflow').click();
    });

    it('Populate just Subtitle', function () {
        cy.contains('Workflows');
        cy.contains('Archive Cataloguing').click();
        cy.contains('Start New').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.get('.workflow-nav-tab.disabled').should('have.length', 4);
        cy.contains('Save and Continue').click();

        // Archive Source Details
        cy.wait(900);
        cy.get('[aria-label="Subtitle"]').should('be.visible').type('Test Subtitle');
        cy.contains('Save and Continue').click();
        cy.contains('Save and Complete Workflow').click();
    });

    
    it('Populate just File Id', function () {
        cy.contains('Workflows');
        cy.contains('Archive Cataloguing').click();
        cy.contains('Start New').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.get('.workflow-nav-tab.disabled').should('have.length', 4);
        cy.contains('Save and Continue').click();

        // Archive Source Details
        cy.wait(900);
        cy.get('[aria-label="File ID (key)"]').should('be.visible').type('TestId');
        cy.contains('Save and Continue').click();
        cy.contains('Save and Complete Workflow').click();
    });


    it('Populate just Archive Source Type', function () {
        cy.contains('Workflows');
        cy.contains('Archive Cataloguing').click();
        cy.contains('Start New').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.get('.workflow-nav-tab.disabled').should('have.length', 4);
        cy.contains('Save and Continue').click();

        // Archive Source Details
        cy.wait(900);
        cy.get('span').contains('Archive Source Type').should('be.visible').siblings('.archive_source_type').click();
        cy.wait(500);
        cy.get('.select2-results__options li').contains('Genre').click();
        cy.wait(500);
        cy.contains('Save and Continue').click();
        cy.contains('Save and Complete Workflow').click();
    });
    
    it('Populate just File Title', function () {
        cy.contains('Workflows');
        cy.contains('Archive Cataloguing').click();
        cy.contains('Start New').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.get('.workflow-nav-tab.disabled').should('have.length', 4);
        cy.contains('Save and Continue').click();

        // Archive Source Details
        cy.wait(900);
        cy.get('input[aria-label="File Title"]').should('be.visible').type('Test Source Name');
        cy.get('[aria-label="Subtitle"]').should('be.visible').type('Test Subtitle');
        cy.get('[aria-label="File ID (key)"]').should('be.visible').type('TestId');
        cy.get('span').contains('Archive Source Type').should('be.visible').siblings('.archive_source_type').click();
        cy.wait(500);
        cy.get('.select2-results__options li').contains('Genre').click();
        cy.get('span').contains('File Status').siblings('.col-xs-12').click();
        cy.wait(500);
        cy.get('.select2-results__options li').contains('Destroyed');
        cy.get('.select2-results__options li').contains('For Review');
        cy.get('.select2-results__options li').contains('Closed');
        cy.get('.select2-results__options li').contains('Open');
        cy.get('.select2-results__options li').contains('Destroyed').click();
        cy.type_ckeditor('editor1', 'test description');
        cy.wait(500);
        cy.contains('Save and Continue').click();

        // Archive Source Creation
        cy.wait(500);
        cy.get('input[aria-label="Author Name"]').should('be.visible').type('Test Author Name');
        cy.get('input[aria-label="Editor Name(s)"]').should('be.visible').type('Test Editor Name');
        cy.get('[aria-label="Start Date"]').scrollIntoView().should('be.visible').click();
        cy.get('input[aria-label="Start Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
        cy.get('[aria-label="End Date"]').scrollIntoView().should('be.visible').click();
        cy.get('input[aria-label="End Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
        cy.type_ckeditor('editor3', 'test statement of responsibility');
        cy.wait(500);
        cy.contains('Save and Continue').click();

        // Repository Storage Location
        cy.wait(1000);
        cy.get('span').contains('Responsible Team').should('be.visible').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Person');
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.get('span').contains('Storage Building Name').should('be.visible').siblings('.col-xs-12').click();
        cy.get('.select2-results__options li').contains('PRONI').click();
        cy.get('input[aria-label="Storage Room Name"]').should('be.visible').type('Test Storage Room Name');
        cy.get('input[aria-label="Storage Shelf Name"]').should('be.visible').type('Test Storage Shelf Name');
        cy.get('input[aria-label="Storage Box Name"]').should('be.visible').type('Test Storage Box Name');
        cy.contains('Save and Continue').click();

        // Archive Loan History
        cy.wait(500);
        cy.get('span').contains('Person or Organization').should('be.visible').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Person');
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.get('[aria-label="Start Date"]').scrollIntoView().should('be.visible').click();
        cy.get('[aria-label="Start Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
        cy.get('[aria-label="End Date"]').scrollIntoView().should('be.visible').click();
        cy.get('[aria-label="End Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
        cy.get('.workflow-component-element').get('.btn.btn-workflow-tile.btn-success').should('be.visible').contains('Add').click();

        // Verify data gets added
        cy.get('.wf-step-multi-tile-container').contains('Archive Loan History').siblings().children('div').children().contains('Test Person');
        // Dates shouldn't be empty
        cy.get('.archive_holder_start_date').last().should('not.have.text');
        cy.get('.archive_holder_start_date').last().should('not.have.text', '');
        cy.get('.archive_holder_end_date').last().should('not.have.text');
        cy.get('.archive_holder_end_date').last().should('not.have.text', '');

        cy.get('.wf-multi-tile-step-card-controls').contains('Remove').click();
        cy.get('.wf-multi-tile-step-list-empty').contains('No Archive Loan History added yet. Add one or multiple Archive Loan History').should('be.visible');

        cy.get('span').contains('Person or Organization').should('be.visible').siblings('.row').click();
        cy.get('.select2-search__field').type('John Doe');
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.get('[aria-label="Start Date"]').scrollIntoView().should('not.have.value');
        cy.get('[aria-label="Start Date"]').scrollIntoView().should('not.have.value', '');
        cy.get('[aria-label="End Date"]').scrollIntoView().should('not.have.value');
        cy.get('[aria-label="End Date"]').scrollIntoView().should('not.have.value', '');
        cy.get('.workflow-component-element').get('.btn.btn-workflow-tile.btn-success').should('be.visible').contains('Add').click();

        // Verify data gets added
        cy.get('.wf-step-multi-tile-container').contains('Archive Loan History').siblings().children('div').children().contains('John Doe');
        cy.get('.archive_holder_start_date').last().should('not.have.text', 'None');
        cy.get('.archive_holder_end_date').last().should('not.have.text', 'None');

        cy.get('.ion-android-cloud-done').siblings().contains('Save').click();
        cy.wait(500);
        cy.contains('Save and Complete Workflow').click();
    });

    it('Populate just File Title', function () {
        cy.contains('Workflows');
        cy.contains('Archive Cataloguing').click();
        cy.contains('Start New').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.get('.workflow-nav-tab.disabled').should('have.length', 4);
        cy.contains('Save and Continue').click();

        // Archive Source Details
        cy.get('span').contains('File Status').siblings('.col-xs-12').click();
        cy.wait(500);
        cy.get('.select2-results__options li').contains('Destroyed');
        cy.get('.select2-results__options li').contains('For Review');
        cy.get('.select2-results__options li').contains('Closed');
        cy.get('.select2-results__options li').contains('Open');
        cy.get('.select2-results__options li').contains('Destroyed').click();
        cy.contains('Save and Continue').click();

        cy.contains('Save and Complete Workflow').click();
    });

    it('Populate just Description', function () {
        cy.contains('Workflows');
        cy.contains('Archive Cataloguing').click();
        cy.contains('Start New').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.get('.workflow-nav-tab.disabled').should('have.length', 4);
        cy.contains('Save and Continue').click();

        // Archive Source Details
        cy.type_ckeditor('editor1', 'test description');
        cy.wait(500);
        cy.contains('Save and Continue').click();
     
        cy.contains('Save and Complete Workflow').click();
    });
    // END OF Archive Source Details Tab individual fields tests

    // START OF Archive Source Creation Tab individual fields tests
    // it('Populate just File Title', function () {
    //     cy.contains('Workflows');
    //     cy.contains('Archive Cataloguing').click();
    //     cy.contains('Start New').click();

    //     // Initial step tab
    //     // Makes sure the autogenerated id is not undefined
    //     cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value');
    //     cy.contains('Resource ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
    //     cy.get('.workflow-nav-tab.disabled').should('have.length', 4);
    //     cy.contains('Save and Continue').click();

    //     // Archive Source Details
    //     cy.contains('Next Step').click();

    //     // Archive Source Creation
    //     cy.wait(500);
    //     cy.get('input[aria-label="Author Name"]').should('be.visible').type('Test Author Name');
    //     cy.get('input[aria-label="Editor Name(s)"]').should('be.visible').type('Test Editor Name');
    //     cy.get('[aria-label="Start Date"]').scrollIntoView().should('be.visible').click();
    //     cy.get('input[aria-label="Start Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
    //     cy.get('[aria-label="End Date"]').scrollIntoView().should('be.visible').click();
    //     cy.get('input[aria-label="End Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
    //     cy.type_ckeditor('editor3', 'test statement of responsibility');
    //     cy.wait(500);
    //     cy.contains('Save and Continue').click();

    //     // Repository Storage Location
    //     cy.wait(1000);
    //     cy.get('span').contains('Responsible Team').should('be.visible').siblings('.row').click();
    //     cy.get('.select2-search__field').type('Test Person');
    //     cy.wait(500);
    //     cy.get('.select2-results__options li').first().click();
    //     cy.get('span').contains('Storage Building Name').should('be.visible').siblings('.col-xs-12').click();
    //     cy.get('.select2-results__options li').contains('PRONI').click();
    //     cy.get('input[aria-label="Storage Room Name"]').should('be.visible').type('Test Storage Room Name');
    //     cy.get('input[aria-label="Storage Shelf Name"]').should('be.visible').type('Test Storage Shelf Name');
    //     cy.get('input[aria-label="Storage Box Name"]').should('be.visible').type('Test Storage Box Name');
    //     cy.contains('Save and Continue').click();

    //     // Archive Loan History
    //     cy.wait(500);
    //     cy.get('span').contains('Person or Organization').should('be.visible').siblings('.row').click();
    //     cy.get('.select2-search__field').type('Test Person');
    //     cy.wait(500);
    //     cy.get('.select2-results__options li').first().click();
    //     cy.get('[aria-label="Start Date"]').scrollIntoView().should('be.visible').click();
    //     cy.get('[aria-label="Start Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
    //     cy.get('[aria-label="End Date"]').scrollIntoView().should('be.visible').click();
    //     cy.get('[aria-label="End Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
    //     cy.get('.workflow-component-element').get('.btn.btn-workflow-tile.btn-success').should('be.visible').contains('Add').click();

    //     // Verify data gets added
    //     cy.get('.wf-step-multi-tile-container').contains('Archive Loan History').siblings().children('div').children().contains('Test Person');
    //     // Dates shouldn't be empty
    //     cy.get('.archive_holder_start_date').last().should('not.have.text');
    //     cy.get('.archive_holder_start_date').last().should('not.have.text', '');
    //     cy.get('.archive_holder_end_date').last().should('not.have.text');
    //     cy.get('.archive_holder_end_date').last().should('not.have.text', '');

    //     cy.get('.wf-multi-tile-step-card-controls').contains('Remove').click();
    //     cy.get('.wf-multi-tile-step-list-empty').contains('No Archive Loan History added yet. Add one or multiple Archive Loan History').should('be.visible');

    //     cy.get('span').contains('Person or Organization').should('be.visible').siblings('.row').click();
    //     cy.get('.select2-search__field').type('John Doe');
    //     cy.wait(500);
    //     cy.get('.select2-results__options li').first().click();
    //     cy.get('[aria-label="Start Date"]').scrollIntoView().should('not.have.value');
    //     cy.get('[aria-label="Start Date"]').scrollIntoView().should('not.have.value', '');
    //     cy.get('[aria-label="End Date"]').scrollIntoView().should('not.have.value');
    //     cy.get('[aria-label="End Date"]').scrollIntoView().should('not.have.value', '');
    //     cy.get('.workflow-component-element').get('.btn.btn-workflow-tile.btn-success').should('be.visible').contains('Add').click();

    //     // Verify data gets added
    //     cy.get('.wf-step-multi-tile-container').contains('Archive Loan History').siblings().children('div').children().contains('John Doe');
    //     cy.get('.archive_holder_start_date').last().should('not.have.text', 'None');
    //     cy.get('.archive_holder_end_date').last().should('not.have.text', 'None');

    //     cy.get('.ion-android-cloud-done').siblings().contains('Save').click();
    //     cy.wait(500);
    //     cy.contains('Save and Complete Workflow').click();
    // });

    // TODO 
    // - Test with each field saved
    // - Try with person and organisation
    // - Open up the created archive and verify information
});
