describe('Going through the Flag For Enforcement Workflow', function () {

    beforeEach(() => {
        cy.login()
        cy.visit('http://localhost:8000/plugins/init-workflow')
    })

    it('Go through the workflow', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        // Starting the workflow
        cy.contains('Save and Continue').click();
        cy.wait(2000);
        cy.get('[aria-label="Case Reference"]').should('be.visible').type('Case Ref');
        cy.contains('Flagged by').siblings('.row').click();
        // Selects the first value in the dropdown. Would be better if we have a pervious test that initates a test person and we can find them by name
        cy.get('.select2-results__options li').first().click();
        cy.get('[aria-label="Flagged Date"]').should('be.visible').click();
    })
})
