describe('Going through the Excavation Site Visit Workflow', function () {

    beforeEach(() => {
        cy.login();
        cy.visit('/plugins/init-workflow');
    });

    it('Create new site visit and go through the workflow and populate all fields', function () {
        cy.contains('Workflows').should('be.visible');
        cy.contains('Excavation Site Visit').click();
        cy.wait(2000);

        // Initial step 1st page
        cy.get('.btn-success').contains('Start New').click();

        // Initial step - ResourceID is disabled/autogenerated (ESV prefix)
        cy.wait(2500);
        cy.get('.card_component.resourceid').contains('ResourceID').should('be.visible');
        cy.get('.form-control').should('be.disabled');

        // Optional link to a parent Activity - if none exist yet this list
        // will just be empty and nothing gets picked.
        cy.contains('Activity').scrollIntoView();
        cy.get('body').then(($body) => {
            if ($body.find('.select2-selection[aria-label^="Activity, "]').length) {
                cy.pickRelationshipFirst('Activity');
                cy.wait(2000);
            }
        });

        cy.workflowNext();

        // Site Visit tab - the 9 default-card configs on this step
        // (Associated Licence/Licence Holder Present/Finds/Survey Methods/
        // Potential Date/Standards Met/Are They Adequate/Stored At/Archive)
        // all pointed at nodegroup ids from a 2024 graph revision that was
        // never migrated into this DB; fixed by remapping to their current
        // equivalents (same names, new ids - e.g. "Finds" nodegroupid
        // 3e311966... -> eb560fbf..., "Archive" 6c21d504... -> ece3ecc9...)
        // after confirming a clean 1:1 name match for all nine.

        cy.get('.card_component.start_date input.form-control').first().click();
        cy.get('.card_component.start_date .input-group-addon').click();

        // get-selected-licence-details relabels "Associated Licences" to
        // "Licence Number" (the widget's own default label matches exactly).
        cy.contains('Licence Number').scrollIntoView();
        cy.pickRelationshipFirst('Licence Number');
        cy.wait(2000);

        // "Person or Organization" -> "HED Inspector" label override.
        cy.contains('HED Inspector').scrollIntoView();
        cy.pickRelationshipFirst('HED Inspector');
        cy.wait(2000);

        cy.setBooleanTrue('licence_holder_present');

        // Description card (cardinality "n") - two fields share the widget
        // label "Description Type" (Activity Description Type and a
        // separate top-level Description Type node), so the dropdown is
        // scoped by alias rather than aria-label to avoid ambiguity.
        cy.get('.card_component.description_type').contains('Select an option').click();
        cy.wait(2000);
        cy.get('.select2-results__option').first().click();
        cy.get('[aria-label="Description"]').click().type('Test activity description');
        cy.get('.btn-success').contains('Add').click();
        cy.wait(2500);

        cy.get('[aria-label="Potential Date of Remains Value"]').click().type('Test potential date');

        cy.setBooleanTrue('finds');
        cy.get('[aria-label="Stored At"]').click().type('Test storage location');
        cy.setBooleanTrue('archive');
        cy.setBooleanTrue('standards_met');
        cy.setBooleanTrue('survey_methods_discussed_');
        cy.setBooleanTrue('are_they_adequate');

        cy.get('.workflow-top-control > .btn-success').contains('Save and Complete Workflow').click();
    });
});
