describe('Going through the Flag For Enforcement Workflow', function () {

    beforeEach(() => {
        cy.login();
        cy.visit('/plugins/init-workflow');
    });

    it('Go through the workflow and populate all fields', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.get('[aria-label="Case Reference"]').should('be.visible').type('Case Ref');
        cy.type_ckeditor('editor2', 'test reason for enforcement');
        cy.contains('Flagged by').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Person');
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.contains('Flagged by').siblings('.row').click();
        cy.get('.select2-search__field').type('John Doe');
        cy.wait(600);
        cy.get('.select2-results__options li').first().click();
        cy.get('[aria-label="Flagged Date"]').scrollIntoView().should('be.visible').click();
        cy.get('[aria-label="Flagged Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
        cy.contains('Select resources').siblings('.row').click();
        cy.get('.select2-results__options li').contains('HA/01').click();
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Case Reference Number:').siblings().should('have.text', 'Case Ref');
        cy.contains('Description:').siblings().should('have.text', 'test reason for enforcement');
        // Only checks if the date we selected is present as the year and month could change
        cy.contains('Flagged Date Value:').siblings().should('contain', '17');
        cy.contains('Actor:').siblings().should('have.text', 'John Doe, Test Person');
        cy.contains('Associated Resources:').siblings().should('have.text', 'HA/01');
        cy.wait(900);
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Enforcement ID', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        
        // Enforcement Details Tab
        cy.wait(900);
        cy.contains('Next Step').click();
        
        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().invoke('text').as('enforcementId')
        cy.contains('Save and Complete Workflow').click();

        console.log(this.enforcementId);
        cy.visit('/search?paging-filter=1&tiles=true');
    });

    it('Workflow with only Case Reference', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.get('[aria-label="Case Reference"]').should('be.visible').type('Case Ref');
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Case Reference Number:').siblings().should('have.text', 'Case Ref');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Reason For Enforcement', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.type_ckeditor('editor2', 'test reason for enforcement');
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Description:').siblings().should('have.text', 'test reason for enforcement');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Flagged By', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.contains('Flagged by').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Person');
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Actor:').siblings().should('have.text', 'Test Person');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Flagged By using Organisation', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.contains('Flagged by').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Organisation');
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Actor:').siblings().should('have.text', 'Test Organisation');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Flagged By using both an Organisation and a Person', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.contains('Flagged by').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Organisation');
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.wait(500);
        cy.contains('Flagged by').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Person');
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Actor:').siblings().should('have.text', 'Test Person, Test Organisation');
        cy.contains('Save and Complete Workflow').click();
    });


    it('Workflow with only Flagged Date', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.get('[aria-label="Flagged Date"]').click();
        cy.get('[aria-label="Flagged Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        // Only checks if the date we selected is present as the year and month could change
        cy.contains('Flagged Date Value:').siblings().should('contain', '17');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Associated Resource', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.wait(900);
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.contains('Select resources').scrollIntoView();
        cy.wait(1000);
        cy.contains('Select resources').siblings('.row').click();
        cy.get('.select2-results__options li').contains('HA/01').click();
        // Selects the first value in the dropdown. Would be better if we have a pervious test that initates a Heritage Asset and uses that by name
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Associated Resources:').siblings().should('have.text', 'HA/01');
        cy.contains('Save and Complete Workflow').click();
    });
});
