describe('Going through the Flag For Enforcement Workflow', function () {

    beforeEach(() => {
        cy.login();
        cy.visit('/plugins/init-workflow');
    });

    it('Go through the workflow and populate all fields', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        // The other 2 tabs should be disabled before we click Save and continue
        cy.get('.workflow-nav-tab.disabled').should('have.length', 2);
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(2500);
        cy.get('[aria-label="Case Reference"]').should('be.visible').type('Case Ref');
        cy.type_ckeditor('editor2', 'test reason for enforcement');
        cy.wait(1500);
        cy.contains('Flagged by').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Person');
        cy.wait(500);
        cy.get('.select2-results__options li').first().click();
        cy.get('[aria-label="Edit related resource Test Person"]').should('be.visible');
        cy.get('[aria-label="Delete relationship to Test Person"]').should('be.visible');
        cy.get('[aria-label="Expand resource report for Test Person"]').should('be.visible');

        cy.contains('Flagged by').siblings('.row').click();
        cy.get('.select2-search__field').type('John Doe');
        cy.wait(600);
        cy.get('.select2-results__options li').first().click();
        cy.get('[aria-label="Edit related resource John Doe"]').should('be.visible');
        cy.get('[aria-label="Delete relationship to John Doe"]').should('be.visible');
        cy.get('[aria-label="Expand resource report for John Doe"]').should('be.visible');

        // Flagged date should be prepopulated
        cy.get('[aria-label="Flagged Date"]').should('not.have.value');
        cy.get('[aria-label="Flagged Date"]').should('not.have.value', '');
        cy.get('[aria-label="Flagged Date"]').scrollIntoView().should('be.visible').click();
        cy.get('[aria-label="Flagged Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
        cy.get('[aria-label="Flagged Date"]').scrollIntoView().should('be.visible').click();
        cy.get('body').click();
        // Value should remain
        cy.get('[aria-label="Flagged Date"]').should('not.have.value');
        cy.get('[aria-label="Flagged Date"]').should('not.have.value', '');

        cy.contains('Select resources').siblings('.row').click();
        cy.get('.select2-results__options li').contains('HA/01 Building1').click();
        cy.get('[aria-label="Edit related resource HA/01 Building1"]').should('be.visible');
        cy.get('[aria-label="Delete relationship to HA/01 Building1"]').should('be.visible');
        cy.get('[aria-label="Expand resource report for HA/01 Building1"]').should('be.visible');

        cy.contains('Select resources').siblings('.row').click();
        cy.get('.select2-results__options li').contains('HA/02 Building2').click();
        cy.get('[aria-label="Edit related resource HA/02 Building2"]').should('be.visible');
        cy.get('[aria-label="Delete relationship to HA/02 Building2"]').should('be.visible');
        cy.get('[aria-label="Expand resource report for HA/02 Building2"]').should('be.visible');

        // cy.contains('Select resources').siblings('.row').click();
        // cy.get('.select2-search__field').type('XXXXXXX');
        // cy.get('.select2-results__option').should('have.length', 1).contains('Create a new Heritage Asset');
        
        // Verify that the two selected resources are in their own rows
        cy.get('.associated_resources').children('.rr-widget').children('.rr-table').children().first().children('.rr-table-row').should('have.length', 2);

        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Case Reference Number:').siblings().should('have.text', 'Case Ref');
        cy.contains('Description:').siblings().should('have.text', 'test reason for enforcement');
        // Only checks if the date we selected is present as the year and month could change
        cy.contains('Flagged Date Value:').siblings().should('contain', '17');
        cy.contains('Actor:').siblings().should('have.text', 'John Doe, Test Person');
        cy.contains('Associated Resources:').siblings().should('have.text', 'HA/02 Building2, HA/01 Building1');
        cy.wait(900);
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Enforcement ID', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        
        // Enforcement Details Tab
        cy.wait(900);
        cy.contains('Save and Continue').click();
        
        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().invoke('text').as('enforcementId')
        cy.contains('Save and Complete Workflow').click();

        console.log(this.enforcementId);
        cy.visit('/search?paging-filter=1&tiles=true');
    });

    it('Workflow with only Case Reference', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.get('[aria-label="Case Reference"]').should('be.visible').type('Case Ref');
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Case Reference Number:').siblings().should('have.text', 'Case Ref');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Reason For Enforcement', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(2500);
        cy.type_ckeditor('editor2', 'test reason for enforcement');
        cy.wait(900);
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Description:').siblings().should('have.text', 'test reason for enforcement');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Flagged By', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(1500);
        cy.contains('Flagged by').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Person');
        cy.wait(900);
        cy.get('.select2-results__options li').first().click();
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Actor:').siblings().should('have.text', 'Test Person');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Flagged By using Organisation', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.contains('Flagged by').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Organisation');
        cy.wait(900);
        cy.get('.select2-results__options li').first().click();
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Actor:').siblings().should('have.text', 'Test Organisation');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Flagged By using both an Organisation and a Person', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(1500);
        cy.contains('Flagged by').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Organisation');
        cy.wait(1000);
        cy.get('.select2-results__options li').first().click();
        cy.wait(1000);
        cy.contains('Flagged by').siblings('.row').click();
        cy.get('.select2-search__field').type('Test Person');
        cy.wait(1000);
        cy.get('.select2-results__options li').first().click();
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Actor:').siblings().should('have.text', 'Test Person, Test Organisation');
        cy.contains('Save and Complete Workflow').click();
    });


    it('Workflow with only Flagged Date', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.wait(900);
        cy.get('[aria-label="Flagged Date"]').click();
        cy.get('[aria-label="Flagged Date"]').siblings('.bootstrap-datetimepicker-widget').contains('17').click();
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        // Only checks if the date we selected is present as the year and month could change
        cy.contains('Flagged Date Value:').siblings().should('contain', '17');
        cy.contains('Save and Complete Workflow').click();
    });

    it('Workflow with only Associated Resource', function () {
        cy.contains('Workflows');
        cy.contains('Flag for Enforcement').click();

        // Initial step tab
        // Makes sure the autogenerated id is not undefined
        cy.wait(900);
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value');
        cy.contains('Enforcement ID').siblings('.col-xs-12').children('input').should('not.have.value', '');
        cy.contains('Save and Continue').click();

        // Enforcement Details Tab
        cy.contains('Select resources').scrollIntoView();
        cy.wait(2000);
        cy.contains('Select resources').siblings('.row').click();
        cy.get('.select2-results__options li').contains('HA/01 Building1').click();
        // Selects the first value in the dropdown. Would be better if we have a pervious test that initates a Heritage Asset and uses that by name
        cy.contains('Save and Continue').click();

        // Enforcement Summary tab
        cy.contains('ResourceID:').siblings().should('not.have.text');
        cy.contains('ResourceID:').siblings().should('not.have.text', '');
        cy.contains('Associated Resources:').siblings().should('have.text', 'HA/01 Building1');
        cy.contains('Save and Complete Workflow').click();
    });
});
