describe('Going through the Respond to Enforcement Workflow', function () {

    beforeEach(() => {
        cy.login();
    });

    it('Create new response and go through the workflow and populate all fields', function () {
        // Respond to Enforcement has no launcher tile on /plugins/init-workflow
        // (it's not in init-workflow.json's own workflows list) and its
        // open-workflow.json entry sets disableStartNew/checkForResourceId,
        // so it can only be reached against an EXISTING Enforcement resource
        // - via the "Open" button on /plugins/view-enforcements, which
        // navigates straight into the workflow with ?resource-id=... set
        // (view-enforcements.js openFlagged()).
        cy.visit('/plugins/view-enforcements');
        cy.get('.add-function-button').contains('Open').first().click();

        // Initial step - ResourceID is disabled/autogenerated
        cy.wait(2500);
        cy.get('.card_component.resourceid').contains('ResourceID').should('be.visible');
        cy.get('.form-control').should('be.disabled');
        cy.workflowNext();

        // Enforcement Details tab - widget label is "Select resources", not
        // "Associated Resources", and it's a resource-instance-list (multi),
        // so scope by alias class rather than pickRelationshipFirst.
        cy.contains('Associated Resources').scrollIntoView();
        cy.pickCardOption('associated_resources');
        cy.wait(2000);

        cy.contains('Enforcement Names').scrollIntoView();
        cy.get('[aria-label="Name"]').click().type('Testing Enforcement Response');
        cy.wait(2000);

        // Single-select reference-select-widget - scope by alias class
        // rather than input[aria-label] (see 12_add_building).
        cy.contains('Enforcement Status').scrollIntoView();
        cy.pickCardOption('status');
        cy.wait(2000);

        // Widget label is "CM Reference", not the node's own name
        // "CM Reference Number".
        cy.contains('Case References').scrollIntoView();
        cy.get('[aria-label="CM Reference"]').click().type('CM-TEST-01');

        cy.contains('Crime References').scrollIntoView();
        cy.get('[aria-label="Crime Reference Number"]').click().type('CRIME-TEST-01');

        // Reason Description / Agreed Action Description / Current Position
        // Description / Result Description all hold a node literally named
        // "Description" - the graph disambiguates them with the aliases
        // description / description_n1 / description_n2 / description_n3,
        // which is what componentCssClasses (card-component.js) turns into
        // these .card_component classes, so scope each lookup accordingly.
        cy.contains('Reason Description').scrollIntoView();
        cy.get('.card_component.description').find('[aria-label="Description"]').click().type('Reason for enforcement');

        cy.contains('Agreed Action Description').scrollIntoView();
        cy.get('.card_component.description_n1').find('[aria-label="Description"]').click().type('Agreed action');

        cy.contains('Current Position Description').scrollIntoView();
        cy.get('.card_component.description_n2').find('[aria-label="Description"]').click().type('Current position');

        cy.contains('Result Description').scrollIntoView();
        cy.get('.card_component.description_n3').find('[aria-label="Description"]').click().type('Result');

        cy.workflowNext();

        // Enforcement Summary tab - read-only review, no inputs
        cy.contains('Created or Modified Resource Instance').should('be.visible');

        cy.get('.workflow-top-control > .btn-success').contains('Save and Complete Workflow').click();
    });
});
