describe('Going through the Respond to Enforcement Workflow', function () {

    beforeEach(() => {
        cy.login();
        cy.visit('/plugins/init-workflow');
    });

    it('Create new response and go through the workflow and populate all fields', function () {
        cy.contains('Workflows').should('be.visible');
        cy.contains('Respond to Enforcement').click();
        cy.wait(2000);

        // Initial step 1st page
        cy.get('.btn-success').contains('Start New').click();

        // Initial step - ResourceID is disabled/autogenerated
        cy.wait(2500);
        cy.get('.card_component.resourceid').contains('ResourceID').should('be.visible');
        cy.get('.form-control').should('be.disabled');
        cy.workflowNext();

        // Enforcement Details tab
        cy.contains('Associated Resources').scrollIntoView();
        cy.pickRelationshipFirst('Associated Resources');
        cy.wait(2000);

        cy.contains('Enforcement Names').scrollIntoView();
        cy.get('[aria-label="Name"]').click().type('Testing Enforcement Response');
        cy.wait(2000);

        cy.contains('Enforcement Status').scrollIntoView();
        cy.get('input[aria-label="Status"]').click();
        cy.wait(2000);
        cy.get('.select2-results__option').first().click();

        cy.contains('Case References').scrollIntoView();
        cy.get('[aria-label="CM Reference Number"]').click().type('CM-TEST-01');

        cy.contains('Crime References').scrollIntoView();
        cy.get('[aria-label="Crime Reference Number"]').click().type('CRIME-TEST-01');

        // Reason Description / Agreed Action Description / Current Position
        // Description / Result Description all hold a node literally named
        // "Description" - the graph disambiguates them with the aliases
        // description / description_n1 / description_n2 / description_n3,
        // which is what componentCssClasses (card-component.js) turns into
        // these .card_component classes, so scope each lookup accordingly.
        cy.contains('Reason Description').scrollIntoView();
        cy.get('.card_component.description').find('[aria-label="Description"]').click().type('Reason for enforcement');

        cy.contains('Agreed Action Description').scrollIntoView();
        cy.get('.card_component.description_n1').find('[aria-label="Description"]').click().type('Agreed action');

        cy.contains('Current Position Description').scrollIntoView();
        cy.get('.card_component.description_n2').find('[aria-label="Description"]').click().type('Current position');

        cy.contains('Result Description').scrollIntoView();
        cy.get('.card_component.description_n3').find('[aria-label="Description"]').click().type('Result');

        cy.workflowNext();

        // Enforcement Summary tab - read-only review, no inputs
        cy.contains('Created or Modified Resource Instance').should('be.visible');

        cy.get('.workflow-top-control > .btn-success').contains('Save and Complete Workflow').click();
    });
});
