from arches.app.functions.base import BaseFunction
from arches.app.models.resource import Resource
from arches.app.models.tile import Tile
from arches.app.models import models
from coral.utils.reference_values import reference_value, selected_list_item_ids

HIERARCHY_TYPE_NODEGROUP = "3e16208d-9560-5998-8ba1-203cd599a5d8"
HIERARCHY_TYPE_NODE = HIERARCHY_TYPE_NODEGROUP

HIERARCHY_STATUATORY = "609367b4-8a68-5f5c-8713-409d33629213"
HIERARCHY_NON_STATUATORY = "34315588-70f4-5643-a4fb-c5ee13a8aa37"

APPLICATION_TYPE_NODEGROUP = "54de6acc-8895-11ea-9067-f875a44e0e11"
APPLICATION_TYPE_NODE = APPLICATION_TYPE_NODEGROUP

# Item ids of the Consultation Application Type list (87feadd5-8d2d-5937-a52e-98d9689501f9),
# regenerated by the v8 controlled-list conversion. Keep in step with
# show-hierarchy-change.js.
STATUTORY_VALUES = [
    "4056ce9f-fac4-5cb8-93f0-e9a8e496aba4", # F - Full
    "c2f571d8-e4fc-58ae-8e13-47f7b217fe10", # O - Outline
    "382043d6-c528-5324-8e32-35ae6c1b267f", # RM - Reserved Matter
]


details = {
    "functionid": "3461bdcc-c5cd-4e5f-8a79-5f621fbbd6ba",
    "name": "Consultation Hierarchy Function",
    "type": "node",
    "description": "Watches the consultation application type nodegroup and sets the correct hierarchy based on that.",
    "defaultconfig": {"triggering_nodegroups": [APPLICATION_TYPE_NODEGROUP]},
    "classname": "ConsultationHierarchyFunction",
    "component": "",
}


class ConsultationHierarchyFunction(BaseFunction):
    def post_save(self, tile, request, context):
        if context and context.get('escape_function', False):
            return

        resource_instance_id = str(tile.resourceinstance.resourceinstanceid)

        application_type = selected_list_item_ids(tile.data.get(APPLICATION_TYPE_NODE))

        if not application_type:
            hierarchy_value = None
        elif application_type & set(STATUTORY_VALUES):
            hierarchy_value = reference_value(HIERARCHY_STATUATORY)
        else:
            hierarchy_value = reference_value(HIERARCHY_NON_STATUATORY)

        hierarchy_tile = None
        try:
            hierarchy_tile = Tile.objects.get(
                resourceinstance_id=resource_instance_id,
                nodegroup_id=HIERARCHY_TYPE_NODEGROUP,
            )
        except Tile.DoesNotExist:
            hierarchy_tile = None
        
        if not hierarchy_tile:
            hierarchy_tile = Tile.objects.get_or_create(
                resourceinstance_id=resource_instance_id,
                nodegroup_id=HIERARCHY_TYPE_NODEGROUP,
                data={
                    HIERARCHY_TYPE_NODEGROUP: hierarchy_value
                },
            )
        else:
            hierarchy_tile.data[HIERARCHY_TYPE_NODEGROUP] = hierarchy_value
            hierarchy_tile.save()

