name: Generate Changelog on PR Merge to Release

on:
  pull_request:
    types: [closed]
    branches:
      - 'release/**'

jobs:
  changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Variables
        id: vars
        run: |
          echo "pr_title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "pr_user=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
          echo "pr_body=$(echo "${{ github.event.pull_request.body }}" | base64 -w 0)" >> $GITHUB_OUTPUT
          echo "pr_head_branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          echo "branch_name=$(echo '${{ github.event.pull_request.base.ref }}' | sed 's|release/||')" >> $GITHUB_OUTPUT
          echo "pr_link=https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        run: |
          # Get branch name from base ref - strip "release/" prefix
          BRANCH_NAME=$(echo '${{ github.event.pull_request.base.ref }}' | sed 's|^release/||')
          CHANGELOG_FILE="changelogs/$BRANCH_NAME.md"
          PR_BODY_FILE="pr_body_${{ github.event.pull_request.number }}.md"
          
          # Create directories and PR body file
          mkdir -p changelogs
          echo "${{ steps.vars.outputs.pr_body }}" | base64 -d > "$PR_BODY_FILE"
          
          # Create changelog file if it doesn't exist
          [ -f "$CHANGELOG_FILE" ] || touch "$CHANGELOG_FILE"
          
          # Run update script with correct parameters
          chmod +x ./.github/workflows/update_changelog.sh
          ./.github/workflows/update_changelog.sh "$PR_BODY_FILE" "$CHANGELOG_FILE" "${{ steps.vars.outputs.pr_title }}" "${{ steps.vars.outputs.pr_user }}" "${{ steps.vars.outputs.pr_number }}" "${{ steps.vars.outputs.pr_link }}"

      - name: Commit Changelog
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add changelogs/
          git commit -m "Update changelog for release: ${{ steps.vars.outputs.branch_name }}" || echo "No changes to commit"
          git push